server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    gateway:
      redis-rate-limiter:
#      配置具体需要流控的路由
        config:
          hello.replenishRate: 2    #每秒流速
          hello.burstCapacity: 2    #桶大小
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false  #注册发现
      routes:
#      - id: winstar-business-account-server
#        uri: lb://WINSTAR-BUSINESS-ACCOUNT-SERVER
#        predicates:
#        - Path=/api/v1/account/*
#      - id: winstar-business-app-server
#        uri: lb://WINSTAR-BUSINESS-APP-SERVER
#        predicates:
#        - Path=/api/v1/app/*
#      - id: winstar-business-cashier-server
#        uri: lb://WINSTAR-BUSINESS-CASHIER-SERVER
#        predicates:
#        - Path=/api/v1/cashier/*
#      - id: winstar-business-goods-server
#        uri: lb://WINSTAR-BUSINESS-GOODS-SERVER
#        predicates:
#        - Path=/api/v1/business/unionGoods/*
#      - id: winstar-business-merchant-server
#        uri: lb://WINSTAR-BUSINESS-MERCHANT-SERVER
#        predicates:
#        - Path=/api/v1/merchant/*
#      - id: winstar-business-order-server
#        uri: lb://WINSTAR-BUSINESS-ORDER-SERVER
#        predicates:
#        - Path=/api/v1/order/*
#      - id: winstar-business-voucher-server
#        uri: lb://WINSTAR-BUSINESS-VOUCHER-SERVER
#        predicates:
#        - Path=/api/v1/voucher/*
      - id: hello
        uri: http://localhost:8082
        predicates:
        - Path=/hello
#        filters:
#          - StripPrefix=1
      default-filters:
        - TokenExtension   #token验证过滤器
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@apiKeyResolver}"  #根据url路径限流
        - name: Hystrix
          args:
            name: fallbackHystrix
            fallbackUri: forward:/failback
  redis:
    host: 192.168.118.111
    port: 6379
    database: 1

#注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://winstar:123456@192.168.118.101:19000/eureka/
    fetch-registry: true
    register-with-eureka: true

# 熔断配置
hystrix:
  #threadpool:
    #default:
      #maximumSize: 400 #此属性设置最大线程池大小。 这是在不开始拒绝HystrixCommands的情况下可以支持的最大并发数。 请注意，此设置仅在您还设置allowMaximumSizeToDivergeFromCoreSize时才会生效。
      #allowMaximumSizeToDivergeFromCoreSize: true #此属性允许maximumSize的配置生效。 那么该值可以等于或高于coreSize。 设置coreSize <maximumSize会创建一个线程池，该线程池可以支持maximumSize并发，但在相对不活动期间将向系统返回线程。
  command:
    default: #对应Hystrix里args的name，默认是"default"
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #设置熔断路由的超时时间


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
    com.winstar: debug
